### PR TITLE
Fixed deeper dependencies

### PR DESCRIPTION
**Pull request by m4w**
It did not work to integrate dependencies which lay two folders above the current file.
I added two tests, which should cover these cases.

### CODE REVIEW

**Comment by KnisterPeter** [comment]
Looks good, but there seem to be some linter errors.

**Comment by m4w** [comment]
Damm, I was to fast. The commit message is unclean now. 
Its very strange, an older file, that I did not touch, was marked with a linter error.

**Comment by KnisterPeter** [comment]
Could be caused by a semver update for tslint. Thats possible.

**Comment by KnisterPeter** [comment]
Released as 0.7.2. Thanks :rocket:

**Pull request merged**
